// Code generated by aocgen; DO NOT EDIT.
package year2022

import (
	"gdejong/advent-of-code-2022/pkg/aoc"
)

func Init() {
	aoc.Register(2022, map[int]aoc.Puzzle{
		1: Day01{},
		2: Day02{},
		3: Day03{},
		4: Day04{},
		5: Day05{},
		6: Day06{},
	})
}
