// Code generated by aocgen; DO NOT EDIT.
package year2022

import (
	"testing"

	"gdejong/advent-of-code-2022/pkg/aoc"
)

func Benchmark2022Day01(b *testing.B) {
	Init()
	input := aoc.TestInput(2022, 1)
	p := aoc.NewPuzzle(2022, 1)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2022Day02(b *testing.B) {
	Init()
	input := aoc.TestInput(2022, 2)
	p := aoc.NewPuzzle(2022, 2)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
